<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proxyman/command/command.proto

namespace Xray\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>xray.app.proxyman.command.ListOutboundsResponse</code>
 */
class ListOutboundsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.core.OutboundHandlerConfig outbounds = 1;</code>
     */
    private $outbounds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Core\OutboundHandlerConfig[] $outbounds
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.OutboundHandlerConfig outbounds = 1;</code>
     * @return RepeatedField<\Xray\Core\OutboundHandlerConfig>
     */
    public function getOutbounds()
    {
        return $this->outbounds;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.OutboundHandlerConfig outbounds = 1;</code>
     * @param \Xray\Core\OutboundHandlerConfig[] $var
     * @return $this
     */
    public function setOutbounds(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Core\OutboundHandlerConfig::class);
        $this->outbounds = $arr;

        return $this;
    }

}

