<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proxyman/command/command.proto

namespace Xray\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>xray.app.proxyman.command.ListInboundsResponse</code>
 */
class ListInboundsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.core.InboundHandlerConfig inbounds = 1;</code>
     */
    private $inbounds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Core\InboundHandlerConfig[] $inbounds
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.InboundHandlerConfig inbounds = 1;</code>
     * @return RepeatedField<\Xray\Core\InboundHandlerConfig>
     */
    public function getInbounds()
    {
        return $this->inbounds;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.InboundHandlerConfig inbounds = 1;</code>
     * @param \Xray\Core\InboundHandlerConfig[] $var
     * @return $this
     */
    public function setInbounds(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Core\InboundHandlerConfig::class);
        $this->inbounds = $arr;

        return $this;
    }

}

