<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proxyman/command/command.proto

namespace Xray\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>xray.app.proxyman.command.ListInboundsRequest</code>
 */
class ListInboundsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isOnlyTags = 1;</code>
     */
    protected $isOnlyTags = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isOnlyTags
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isOnlyTags = 1;</code>
     * @return bool
     */
    public function getIsOnlyTags()
    {
        return $this->isOnlyTags;
    }

    /**
     * Generated from protobuf field <code>bool isOnlyTags = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOnlyTags(bool $var)
    {
        $this->isOnlyTags = $var;

        return $this;
    }

}

